language: minimal

sudo: required

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t nanzhong/workstation:latest .
  - docker tag nanzhong/workstation:latest "nanzhong/workstation:$TRAVIS_COMMIT"
  - docker push nanzhong/workstation:latest
  - docker push "nanzhong/workstation:$TRAVIS_COMMIT"
