language: minimal
sudo: required
services:
- docker
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- docker build -t $DOCKER_IMAGE:latest .
after_script:
- docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$TRAVIS_COMMIT
- docker push $DOCKER_IMAGE:latest
- docker push $DOCKER_IMAGE:$TRAVIS_COMMIT
