#!/bin/sh

/usr/local/bin/notmuch new
new=`~/bin/newmail do`

if [ $new -gt 0 ]
then
   /usr/local/bin/terminal-notifier -title 'offlineimap' -subtitle 'nzhong@digitalocean.com' -message "You have $new new email(s)!" -group offlineimap-do
fi
