theme = "nan"

[editor]
rulers = [80]
color-modes = true
insert-final-newline = false
popup-border = "all"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.whitespace]
render = "none"

[keys.normal]
C-b = ":pipe-to tmux split-window -v helix-git-blame"
C-l = ":pipe-to tmux split-window -v helix-gh-browse"